version: 2
  jobs:
    test:
      docker:
        - image: circleci/node:12.16
      steps:
        - checkout
        - run: echo "Running tests"
        - run: npm install
        - run: npm test
    build:
      docker:
        - image: circleci/node:12.16
      steps:
        - checkout
        - run: echo "build storybook project"
        - npm install
        - npm run build-storybook

workflows:
  version: 2
    test_build:
      jobs:
        - test
        - build:
          requires:
            - test